### ISSUE TITLE
Please drop `machine-os-content` reference

### ISSUE THREAD

**Issue by cgwalters** [openshift/driver-toolkit#101]
xref https://github.com/openshift/machine-config-operator/pull/3364
https://issues.redhat.com/browse/MCO-392?focusedCommentId=21045301&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21045301

**Comment by qbarrand** [comment]
Reopening this issue with #103.
We need more guidance on how to replace `machine-os-content`, which provides an essential piece in the way DTK is currently released.

**Comment by cgwalters** [comment]
OK, let's discuss design in https://issues.redhat.com/browse/MCO-392?focusedCommentId=21048335&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21048335 or so?  I see the desire for a tag for "default operating system".  But I'd still really like to push for a world where we ship *both* `rhel-coreos-8` and `rhel-coreos-9` for example, and so anything using the "default" tag would then need to consider whether it actually needs to look at all possible operating system tags for example.

**Comment by ybettan** [comment]
/cc @ybettan 
So I can keep track of it.

**Comment by ybettan** [comment]
I have added [documentation](https://github.com/openshift/driver-toolkit/pull/110) of all the moving parts of that imagestream.

**Comment by ybettan** [comment]
/remove lifecycle/stale
After some discussion the first step of the solution will be to try to user `rhel-coreos-8` or `rhel-coreos-9` in the `image-refrences` instead of `machine-os-content`.

This will require adding the `io.openshift.build.versions` label to the `rhel-coreos-<8|9>` and replace the primary source in ART's repo.

Additional info can be found at https://redhat-internal.slack.com/archives/C02CU30L7GF/p1676467754327349

**Comment by sosiouxme** [comment]
it's just `rhel-coreos` now. but `io.openshift.build.versions` label isn't there:
```
🐚 oc image info $(oc adm release info --image-for rhel-coreos 4.13.0-rc.5) | grep version
            org.opencontainers.image.version=413.92.202304191831-0
            version=413.92.202304191831-0
```

**Comment by cgwalters** [comment]
Yeah, this is messy...there's a whole lot interlocked here.  We have a [build time option](https://github.com/coreos/coreos-assembler/pull/3153) to add it and I tried to [use it here](https://github.com/openshift/os/pull/1048) but then we [reverted here](https://github.com/openshift/os/pull/1084) because we discovered that `oc adm release new` barfs if there are *two* images with the same `machine-os` label...

And that's where it stands, I think we'd need to fix `oc adm release new`.

**Comment by sosiouxme** [comment]
perhaps DTK could change to looking at `org.opencontainers.image.version` label for 4.13+?
not sure the significance of these labels

**Comment by ybettan** [comment]
@sosiouxme DTK isn't doing any of this stuff at all.
All we are doing is to add the [machine-os-content snapshot](https://github.com/openshift/driver-toolkit/blob/cafed17b0c2b4cf8d8310304888787ed7adf7474/manifests/01-openshift-imagestream.yaml#L18).

I think that `oc adm new...` is the one responsible for the substitution so this change will probably need to be done there.

I don't mind changing the shapshot to any other container if needed to make it work.

**Comment by jlebon** [comment]
The RHCOS pipeline is still building and maintaining the path to this container image. Would be helpful if we could finally nuke it completely from our deliverables. (E.g. our pipeline just tripped on a bug trying to build that container: https://github.com/coreos/coreos-assembler/issues/3635).

Naive question: rather than trying to solve the "how to ship multiple images with proper labels" part (which requires changes to `oc`), can we not stage the changes in both RHCOS and DTK and flip the switch roughly at the same time so that the new container has `machine-os` and the old container is gone?

It sounds like the blocker was on the fact that we'll eventually want the `oc` changes anyway so that we can ship multiple OS versions in the future, but it seems like for now we don't have to block on that to remove the legacy oscontainer.

**Comment by ybettan** [comment]
> Naive question: rather than trying to solve the "how to ship multiple images with proper labels" part (which requires changes to oc), can we not stage the changes in both RHCOS and DTK and flip the switch roughly at the same time so that the new container has machine-os and the old container is gone?

I don't anticipate an issue from the DTK side doing it.
AFAIK, if:
1. `machine-oc-content` is removed
2. `"io.openshift.build.versions": "machine-os=<ocp version>.<rhel version>.<timestamp>"` is added to `rhel-coreos` instead
3. [dtk-image-references](https://github.com/openshift/driver-toolkit/blob/cafed17b0c2b4cf8d8310304888787ed7adf7474/manifests/image-references#L12) is modified to point to `rhel-coreos` image instead of `machine-os-content`
Then we should be good to go.

In case the `io.openshift.build.versions` needs to be added to any other container in the payload in the future, then we can address the `oc` issue.

**Comment by jlebon** [comment]
I threw up https://github.com/openshift/os/pull/1374 and https://github.com/openshift/driver-toolkit/pull/135. I invite folks who have more context on this issue to review those. On the ART side, it looks like https://issues.redhat.com/browse/ART-4932 is still the ticket tracking the cleanups needed there.
