### ISSUE TITLE
how to install flex and bison package in dtk image on OCP-4.10.17 cluster

### ISSUE THREAD

**Issue by Walnux** [openshift/driver-toolkit#89]
I am building the linux kernel driver modules in dtk image on OCP-4.10.17 cluster

The driver modules building needs flex and bison package. But these two packages can't be installed in the dtk image. 

I can install them on RHEL-8.5, looks like flex and bison packages are from repo rhel-8-for-x86_64-appstream-rpms on RHEL-8.5
 
So I'd like to know what is the proper way to install flex and bison in DTK image container running on OCP-4.10.17  

BTW, since flex and bison are the tools needed by kernel building, could they be included in DTK image by default?

**Comment by ybettan** [comment]
Hello @Walnux.

The driver-toolkit is part of the OCP release and therefore built with it.

As part of the build process, the yum repositories are injected to DTK, all packages are installed and then the yum repositories are removed from the image.

The current recommendation, is that you pull the repositories you need manually inside your driver-container image for any additional package installation.

Regarding `flex` and `bison`, we will need to check those out. If those are potentially widely used across different drivers that may be a strong case to include them in DTK out of the box.

**Comment by chaitanya1731** [comment]
Hi, totally agree with @Walnux here, `flex` and `bison` are indeed important packages that are needed for kernel building. I see these packages are a part of `rhel-8-for-x86_64-appstream-rpms` (Repo Name - Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)) repository, but the driver toolkit is based on the UBI Base OS repository `ubi-8-baseos` Name - Red Hat Universal Base Image 8 (RPMs) - BaseOS that doesn't support `flex` and `bison`. 

Currently, I am able to install them manually like - 
```
# install bison
ARG BISON_VERSION=3.8
ADD http://ftp.gnu.org/gnu/bison/bison-${BISON_VERSION}.tar.gz /bison/
RUN tar -xzvf /bison/bison-${BISON_VERSION}.tar.gz -C /bison/ && cd /bison/bison-${BISON_VERSION} && ./configure && make && make install
```

```
# install flex
ARG FLEX_VERSION=2.6.4
ADD https://github.com/westes/flex/files/981163/flex-${FLEX_VERSION}.tar.gz /flex/
RUN tar -xzvf /flex/flex-${FLEX_VERSION}.tar.gz -C /flex/ && cd /flex/flex-${FLEX_VERSION} && ./configure && make && make install
```
Could you share some easier way to install these so that we dont have to edit the dockerfile everytime?
But it would be great if these packages are the part of driver toolkit image as well.

**Comment by ybettan** [comment]
Hi @chaitanya1731

What you did is a good option as well.

You can also do:
```
ADD <repos url> /etc/yum.repos.d/
RUN dnf install ...
```

If you don't want to modify the Dockerfile, you can also build the image while mounting the host's yum repos. For example you can run:
```
podman build -t <img name> -v /etc/yum.repos.d/:/etch/yum.repos.d .
```
(I may have some mistakes in the command but this is the idea).

Regarding adding those packages in DTK I will let you know if this become possible.
```

**Comment by chaitanya1731** [comment]
Hi @ybettan, any updates on adding these packages in DTK by default?

**Comment by chaitanya1731** [comment]
Hi @ybettan we need `flex` and `bison` to build the Kernel Modules that are a part of GPU driver components.

**Comment by ybettan** [comment]
FYI @chaitanya1731
